### ISSUE TITLE
Is it possible to preread pub/sub request and forward to different MQTT broker?

### ISSUE THREAD

**Issue by tsigcn** [weida/nginx_mqtt_preread_module#1]
I have seen that nginx_mqtt_preread_module can read mqtt_conn infomation well.
So is it possible for nginx to preread pub/sub request and forward them to different MQTT broker in one connection?

For example, pub request forward to port 1883 and sub request forward to port 8883?

Thanks and regards.

**Comment by weida** [comment]
NGINX doesn't support dynamic upstream selecttion based on message types by default, Additionally, you will need to manage long connections for each broker to ensure efficient reuse, which reuires developing or extending the stream module.

**Comment by weida** [comment]
> NGINX doesn't support dynamic upstream selecttion based on message types by default, Additionally, you will need to manage long connections for each broker to ensure efficient reuse, which reuires developing or extending the stream module.

**Comment by tsigcn** [comment]
Got it and thanks for your great support!
